import { Injectable } from '@angular/core';
import { ILink, IOptionSelect } from 'src/app/modules/admin/store/types';

export interface IConstOption {
  title: string;
  value: any;
}
export interface IOptionMultiple {
  title: string;
  value: string | number | any;
  id?: number;
  fontExternalId?: string;
}

export interface IConstOptionCountry {
  title: string;
  value: any;
  taxTypes: string[] | IConstOption[];
}

@Injectable({
  providedIn: 'root',
})
export class ConstsService {
  public navigationLinks: ILink[] = [
    { link: '/dashboard', name: 'Dashboard', svgName: 'gm-dashboard', active: true },
    { link: '/creative-hub', name: 'Creative Hub', svgName: 'gm-creative-hub', active: false },
    { link: '/copywriting', name: 'Copywriting', svgName: '', active: false },
    { link: '/templates', name: 'Templates', svgName: '', active: false },
    { link: '/assets-tab', name: 'Assets', svgName: '', active: false },
    { link: '/complete-ad', name: 'Ad Composer', svgName: '', active: false },
    { link: '/control-hub', name: 'Control Hub', svgName: 'gm-control-hub', active: false },
    { link: '/ad-ready', name: 'Ready Ad', svgName: '', active: false },
    { link: '/data-hub', name: 'Data Hub', svgName: 'gm-data', active: false },
  ];

  public creativeHubLinks: ILink[] = [
    { link: '/copywriting', name: 'Copywriting', svgName: '', active: false },
    { link: '/templates', name: 'Templates', svgName: '', active: false },
    { link: '/assets-tab', name: 'Assets', svgName: '', active: false },
    { link: '/complete-ad', name: 'Ad Composer', svgName: '', active: false },
  ];

  public controlHubLinks: ILink[] = [{ link: '/ad-ready', name: 'Ready Ad', svgName: '', active: false }];

  public perPageOptions: IConstOption[] = [
    { value: 5, title: '5' },
    { value: 10, title: '10' },
    { value: 20, title: '20' },
  ];

  public textTagsIds: any = {};

  public adsFormatOptions: IConstOption[] = [
    { value: null, title: 'All' },
    { value: 'image', title: 'Image' },
    { value: 'video', title: 'Video' },
  ];

  public typeOptions: IConstOption[] = [
    { value: 'happy', title: 'Happy' },
    { value: 'sad', title: 'Sad' },
    { value: 'christmas', title: 'Christmas' },
  ];

  public stagesOptions: IConstOption[] = [
    { value: 'tof', title: 'TOF' },
    { value: 'fot', title: 'FOT' },
    { value: 'oft', title: 'OFT' },
  ];

  public typeAssetsOptions: IConstOption[] = [
    { value: 'image', title: 'Image' },
    { value: 'video', title: 'Video' },
  ];

  public occasionOptions: IConstOption[] = [
    { value: 'all', title: 'All' },
    { value: 'blackFriday', title: 'Black friday' },
    { value: 'easter', title: 'Easter' },
  ];

  public sortingOptions: IConstOption[] = [
    { value: 'bestConverting', title: 'Best Converting' },
    { value: 'bestQuality', title: 'Best Quality' },
  ];

  public adsButtonTextOptions: IConstOption[] = [
    { value: 'See more', title: 'See more' },
    { value: 'Buy now', title: 'Buy now' },
  ];

  public adAccountOptions: IConstOption[] = [
    { value: 'learnMore', title: 'Learn More' },
    { value: 'readMore', title: 'Read More' },
  ];
  public adPageOptions: IConstOption[] = [
    { value: '1', title: '1' },
    { value: '2', title: '2' },
  ];
  public adPixelOptions: IConstOption[] = [
    { value: 'example 1', title: 'example 1' },
    { value: 'example 2', title: 'example 2' },
  ];
  public adOptimiseForOptions: IConstOption[] = [
    { value: 'text', title: 'Text' },
    { value: 'image', title: 'Image' },
  ];
  public adCampaignNameOptions: IConstOption[] = [
    { value: 'Example 1', title: 'Example 1' },
    { value: 'Example 2', title: 'Example 2' },
  ];
  public adAdsetNameOptions: IConstOption[] = [
    { value: 'Lorem', title: 'Lorem' },
    { value: 'Ipsuem', title: 'Ipsuem' },
  ];
  public adAudiencetOptions: IConstOption[] = [
    { value: 'Auojiu', title: 'Auojiu' },
    { value: 'Iadijnd', title: 'Iadijnd' },
  ];
  public languageOptions: IConstOption[] = [
    { value: 'polish', title: 'Polish' },
    { value: 'english', title: 'English' },
  ];
  public toneOptions: IConstOption[] = [
    { value: 'funny', title: 'funny' },
    { value: 'sad', title: 'sad' },
  ];

  public goalOptions: IConstOption[] = [
    { value: 'Prospecting', title: 'Prospecting' },
    { value: 'Retargeting', title: 'Retargeting' },
  ];

  public numberOfVariantsOptions: IConstOption[] = [
    { value: 1, title: '1 variants' },
    { value: 2, title: '2 variants' },
    { value: 3, title: '3 variants' },
  ];
  public creativityLevelOptions: IConstOption[] = [
    { value: 'default', title: 'Optimal' },
    { value: 'none ', title: 'None' },
    { value: 'low', title: 'Low' },
    { value: 'medium', title: 'Medium' },
    { value: 'high', title: 'High' },
    { value: 'max', title: 'Max' },
  ];

  public assetTypesOptions: IConstOption[] = [
    { value: 'all', title: 'All' },
    { value: 'image', title: 'Image' },
    { value: 'text', title: 'Text' },
    // { value: 'font', title: 'Font' },
    { value: 'video', title: 'Video' },
  ];

  public assetTagsOptions: IConstOption[] = [
    { value: 'tag1', title: 'Tag 1' },
    { value: 'tag2 ', title: 'Tag 2' },
    { value: 'tag3', title: 'Tag 3' },
  ];

  public textTagsRequired: IOptionSelect[] = [];

  public brandIcons: string[] = [
    'gm-bezier-curve',
    'gm-bounding-box',
    'gm-circle-half',
    'gm-drop-half',
    'gm-eraser',
    'gm-eye-dropper-sample',
    'gm-flow-arrow',
    'gm-grid-four',
    'gm-highlighter-circle',
    'gm-intersect',
    'gm-layout',
    'gm-line-segments',
    'gm-magic-wand',
    'gm-marker-circle',
    'gm-paint-brush',
    'gm-paint-brush-broad',
    'gm-paint-bucket',
    'gm-paint-roller',
    'gm-pen-straight',
    'gm-pen-brand',
    'gm-palette',
    'gm-pencil-circle',
    'gm-polygon',
    'gm-swatches',
  ];

  public taxTypesOptions: IConstOption[] = [
    { value: 'ae_trn', title: 'United Arab Emirates TRN' },
    { value: 'au_abn', title: 'Australian Business Number (AU ABN)' },
    { value: 'au_arn', title: 'Australian Taxation Office Reference Number' },
    { value: 'bg_uic', title: 'Bulgaria Unified Identification Code' },
    { value: 'br_cnpj', title: 'Brazilian CNPJ number' },
    { value: 'br_cpf', title: 'Brazilian CPF number' },
    { value: 'ca_bn', title: 'Canadian BN' },
    { value: 'ca_gst_hst', title: 'Canadian GST/HST number' },
    { value: 'ca_pst_bc', title: 'Canadian PST number (British Columbia)' },
    { value: 'ca_pst_mb', title: 'Canadian PST number (Manitoba)' },
    { value: 'ca_pst_sk', title: 'Canadian PST number (Saskatchewan)' },
    { value: 'ca_qst', title: 'Canadian QST number (Québec)' },
    { value: 'ch_vat', title: 'Switzerland VAT number' },
    { value: 'cl_tin', title: 'Chilean TIN' },
    { value: 'eg_tin', title: 'Egyptian Tax Identification Number' },
    { value: 'es_cif', title: 'Spanish NIF number (previously Spanish CIF number)' },
    { value: 'eu_oss_vat', title: 'European One Stop Shop VAT number for non-Union scheme' },
    { value: 'eu_vat', title: 'European VAT number' },
    { value: 'gb_vat', title: 'United Kingdom VAT number' },
    { value: 'ge_vat', title: 'Georgian VAT' },
    { value: 'hk_br', title: 'Hong Kong BR number' },
    { value: 'hu_tin', title: 'Hungary tax number (adószám)' },
    { value: 'id_npwp', title: 'Indonesian NPWP number' },
    { value: 'il_vat', title: 'Israel VAT' },
    { value: 'in_gst', title: 'Indian GST number' },
    { value: 'is_vat', title: 'Icelandic VAT' },
    { value: 'jp_cn', title: 'Japanese Corporate Number (*Hōjin Bangō*)' },
    { value: 'jp_rn', title: 'Japanese Registered Foreign Businesses Registration Number (*Tōroku Kokugai Jigyōsha no Tōroku Bangō*)' },
    { value: 'jp_trn', title: 'Japanese Tax Registration Number (*Tōroku Bangō*)' },
    { value: 'ke_pin', title: 'Kenya Revenue Authority Personal Identification Number' },
    { value: 'kr_brn', title: 'Korean BRN' },
    { value: 'li_uid', title: 'Liechtensteinian UID number' },
    { value: 'mx_rfc', title: 'Mexican RFC number' },
    { value: 'my_frp', title: 'Malaysian FRP number' },
    { value: 'my_itn', title: 'Malaysian ITN' },
    { value: 'my_sst', title: 'Malaysian SST number' },
    { value: 'no_vat', title: 'Norwegian VAT number' },
    { value: 'nz_gst', title: 'New Zealand GST number' },
    { value: 'ph_tin', title: 'Philippines Tax Identification Number' },
    { value: 'ru_inn', title: 'Russian INN' },
    { value: 'ru_kpp', title: 'Russian KPP' },
    { value: 'sa_vat', title: 'Saudi Arabia VAT' },
    { value: 'sg_gst', title: 'Singaporean GST' },
    { value: 'sg_uen', title: 'Singaporean UEN' },
    { value: 'si_tin', title: 'Slovenia tax number (davčna številka)' },
    { value: 'th_vat', title: 'Thai VAT' },
    { value: 'tr_tin', title: 'Turkish Tax Identification Number' },
    { value: 'tw_vat', title: 'Taiwanese VAT' },
    { value: 'ua_vat', title: 'Ukrainian VAT' },
    { value: 'us_ein', title: 'United States EIN' },
    { value: 'us_ein', title: 'South African VAT number' },
  ];

  public countriesOptions: IConstOptionCountry[] = [
    {
      value: 'Australia',
      title: 'Australia',
      taxTypes: [
        { title: 'Australian Business Number (AU ABN)', value: 'au_abn' },
        { title: 'Australian Taxation Office Reference Number', value: 'au_arn' },
      ],
    },
    { value: 'Austria', title: 'Austria', taxTypes: ['eu_vat'] },
    { value: 'Belgium', title: 'Belgium', taxTypes: ['eu_vat'] },
    {
      value: 'Brazil',
      title: 'Brazil',
      taxTypes: [
        { value: 'br_cnpj', title: 'Brazilian CNPJ number' },
        { value: 'br_cpf', title: 'Brazilian CPF number' },
      ],
    },
    {
      value: 'Bulgaria',
      title: 'Bulgaria',
      taxTypes: [
        { value: 'bg_uic', title: 'Bulgaria Unified Identification Code' },
        { value: 'eu_vat', title: 'European VAT number' },
      ],
    },
    {
      value: 'Canada',
      title: 'Canada',
      taxTypes: [
        { value: 'ca_bn', title: 'Canadian BN' },
        { value: 'ca_gst_hst', title: 'Canadian GST/HST number' },
        { value: 'ca_pst_bc', title: 'Canadian PST number (British Columbia)' },
        { value: 'ca_pst_mb', title: 'Canadian PST number (Manitoba)' },
        { value: 'ca_pst_sk', title: 'Canadian PST number (Saskatchewan)' },
        { value: 'ca_qst', title: 'Canadian QST number (Québec)' },
      ],
    },
    { value: 'Chile', title: 'Chile', taxTypes: ['cl_tin'] },
    { value: 'Croatia', title: 'Croatia', taxTypes: ['eu_vat'] },
    { value: 'Cyprus', title: 'Cyprus', taxTypes: ['eu_vat'] },
    { value: 'Czech', title: 'Czech', taxTypes: ['eu_vat'] },
    { value: 'Denmark', title: 'Denmark', taxTypes: ['eu_vat'] },
    { value: 'Egypt', title: 'Egypt', taxTypes: ['eg_tin'] },
    { value: 'Estonia', title: 'Estonia', taxTypes: ['eu_vat'] },
    { value: 'EU', title: 'EU', taxTypes: ['eu_oss_vat'] },
    { value: 'Finland', title: 'Finland', taxTypes: ['eu_vat'] },
    { value: 'France', title: 'France', taxTypes: ['eu_vat'] },
    { value: 'Georgia', title: 'Georgia', taxTypes: ['ge_vat'] },
    { value: 'Germany', title: 'Germany', taxTypes: ['eu_vat'] },
    { value: 'Greece', title: 'Greece', taxTypes: ['eu_vat'] },
    { value: 'Hong Kong', title: 'Hong Kong', taxTypes: ['hk_br'] },
    {
      value: 'Hungary',
      title: 'Hungary',
      taxTypes: [
        { value: 'hu_tin', title: 'Hungary tax number (adószám)' },
        { value: 'eu_vat', title: 'European VAT number' },
      ],
    },
    { value: 'Iceland', title: 'Iceland', taxTypes: ['is_vat'] },
    { value: 'India', title: 'India', taxTypes: ['in_gst'] },
    { value: 'Indonesia', title: 'Indonesia', taxTypes: ['id_npwp'] },
    { value: 'Ireland', title: 'Ireland', taxTypes: ['eu_vat'] },
    { value: 'Israel', title: 'Israel', taxTypes: ['il_vat'] },
    { value: 'Italy', title: 'Italy', taxTypes: ['eu_vat'] },
    {
      value: 'Japan',
      title: 'Japan',
      taxTypes: [
        { value: 'jp_cn', title: 'Japanese Corporate Number (*Hōjin Bangō*)' },
        { value: 'jp_rn', title: 'Japanese Registered Foreign Businesses Registration Number (*Tōroku Kokugai Jigyōsha no Tōroku Bangō*)' },
        { value: 'jp_trn', title: 'Japanese Tax Registration Number (*Tōroku Bangō*)' },
      ],
    },
    { value: 'Kenya', title: 'Kenya', taxTypes: ['ke_pin'] },
    { value: 'Latvia', title: 'Latvia', taxTypes: ['eu_vat'] },
    { value: 'Liechtenstein', title: 'Liechtenstein', taxTypes: ['li_uid'] },
    { value: 'Lithuania', title: 'Lithuania', taxTypes: ['eu_vat'] },
    { value: 'Luxembourg', title: 'Luxembourg', taxTypes: ['eu_vat'] },
    {
      value: 'Malaysia',
      title: 'Malaysia',
      taxTypes: [
        { value: 'my_frp', title: 'Malaysian FRP number' },
        { value: 'my_itn', title: 'Malaysian ITN' },
        { value: 'my_sst', title: 'Malaysian SST number' },
      ],
    },
    { value: 'Malta', title: 'Malta', taxTypes: ['eu_vat'] },
    { value: 'Mexico', title: 'Mexico', taxTypes: ['mx_rfc'] },
    { value: 'Netherlands', title: 'Netherlands', taxTypes: ['eu_vat'] },
    { value: 'New Zealand', title: 'New Zealand', taxTypes: ['nz_gst'] },
    { value: 'Norway', title: 'Norway', taxTypes: ['no_vat'] },
    { value: 'Philippines', title: 'Philippines', taxTypes: ['ph_tin'] },
    { value: 'Poland', title: 'Poland', taxTypes: ['eu_vat'] },
    { value: 'Portugal', title: 'Portugal', taxTypes: ['eu_vat'] },
    { value: 'Romania', title: 'Romania', taxTypes: ['eu_vat'] },
    {
      value: 'Russia',
      title: 'Russia',
      taxTypes: [
        { value: 'ru_inn', title: 'Russian INN' },
        { value: 'ru_kpp', title: 'Russian KPP' },
      ],
    },
    { value: 'Saudi Arabia', title: 'Saudi Arabia', taxTypes: ['sa_vat'] },
    {
      value: 'Singapore',
      title: 'Singapore',
      taxTypes: [
        { value: 'sg_gst', title: 'Singaporean GST' },
        { value: 'sg_uen', title: 'Singaporean UEN' },
      ],
    },
    { value: 'Slovakia', title: 'Slovakia', taxTypes: ['eu_vat'] },
    {
      value: 'Slovenia',
      title: 'Slovenia',
      taxTypes: [
        { value: 'eu_vat', title: 'European VAT number' },
        { value: 'si_tin', title: 'Slovenia tax number (davčna številka)' },
      ],
    },
    { value: 'South Africa', title: 'South Africa', taxTypes: ['za_vat'] },
    { value: 'South Korea', title: 'South Korea', taxTypes: ['kr_brn'] },
    {
      value: 'Spain',
      title: 'Spain',
      taxTypes: [
        { value: 'es_cif', title: 'Spanish NIF number (previously Spanish CIF number)' },
        { value: 'eu_vat', title: 'European VAT number' },
      ],
    },
    { value: 'Sweden', title: 'Sweden', taxTypes: ['eu_vat'] },
    { value: 'Switzerland', title: 'Switzerland', taxTypes: ['ch_vat'] },
    { value: 'Taiwan', title: 'Taiwan', taxTypes: ['tw_vat'] },
    { value: 'Thailand', title: 'Thailand', taxTypes: ['th_vat'] },
    { value: 'Turkey', title: 'Turkey', taxTypes: ['tr_tin'] },
    { value: 'Ukraine', title: 'Ukraine', taxTypes: ['ua_vat'] },
    { value: 'United Arab Emirates', title: 'United Arab Emirates', taxTypes: ['ae_trn'] },
    {
      value: 'United Kingdom',
      title: 'United Kingdom',
      taxTypes: [
        { value: 'gb_vat', title: 'United Kingdom VAT number' },
        { value: 'eu_vat', title: 'Northern Ireland VAT number' },
      ],
    },
    { value: 'United States', title: 'United States', taxTypes: ['us_ein'] },
  ];

  public stabilityAIEnginesOptions: IConstOption[] = [
    { value: 'stable-diffusion-xl-beta-v2-2-2', title: 'Stable Diffusion v2.2.2-XL Beta' },
    { value: 'stable-diffusion-512-v2-1', title: 'Stable Diffusion v2.1' },
  ];

  public stabilityAIStylesOptions: IConstOption[] = [
    { value: '3d-model', title: '3D model' },
    { value: 'analog-film', title: 'Analog film' },
    { value: 'anime', title: 'Anime' },
    { value: 'cinematic', title: 'Cinematic' },
    { value: 'comic-book', title: 'Comic book' },
    { value: 'digital-art', title: 'Digital art' },
    { value: 'enhance', title: 'Enhance' },
    { value: 'fantasy-art', title: 'Fantasy art' },
    { value: 'isometric', title: 'Isometric' },
    { value: 'line-art', title: 'Line art' },
    { value: 'low-poly', title: 'Low poly' },
    { value: 'modeling-compound', title: 'Modelling compound' },
    { value: 'neon-punk', title: 'Neon punk' },
    { value: 'origami', title: 'Origami' },
    { value: 'photographic', title: 'Photographic' },
    { value: 'pixel-art', title: 'Pixel art' },
    { value: 'tile-texture', title: 'Tile texture' },
  ];

  public googleIconsOptions: string[] = [
    '3d_rotation',
    'ac_unit',
    'access_alarm',
    'access_alarms',
    'access_time',
    'accessibility',
    'accessible',
    'account_balance',
    'account_balance_wallet',
    'account_box',
    'account_circle',
    'adb',
    'add',
    'add_a_photo',
    'add_alarm',
    'add_alert',
    'add_box',
    'add_circle',
    'add_circle_outline',
    'add_location',
    'add_shopping_cart',
    'add_to_photos',
    'add_to_queue',
    'adjust',
    'airline_seat_flat',
    'airline_seat_flat_angled',
    'airline_seat_individual_suite',
    'airline_seat_legroom_extra',
    'airline_seat_legroom_normal',
    'airline_seat_legroom_reduced',
    'airline_seat_recline_extra',
    'airline_seat_recline_normal',
    'airplanemode_active',
    'airplanemode_inactive',
    'airplay',
    'airport_shuttle',
    'alarm',
    'alarm_add',
    'alarm_off',
    'alarm_on',
    'album',
    'all_inclusive',
    'all_out',
    'android',
    'announcement',
    'apps',
    'archive',
    'arrow_back',
    'arrow_downward',
    'arrow_drop_down',
    'arrow_drop_down_circle',
    'arrow_drop_up',
    'arrow_forward',
    'arrow_upward',
    'art_track',
    'aspect_ratio',
    'assessment',
    'assignment',
    'assignment_ind',
    'assignment_late',
    'assignment_return',
    'assignment_returned',
    'assignment_turned_in',
    'assistant',
    'assistant_photo',
    'attach_file',
    'attach_money',
    'attachment',
    'audiotrack',
    'autorenew',
    'av_timer',
    'backspace',
    'backup',
    'battery_alert',
    'battery_charging_full',
    'battery_full',
    'battery_std',
    'battery_unknown',
    'beach_access',
    'beenhere',
    'block',
    'bluetooth',
    'bluetooth_audio',
    'bluetooth_connected',
    'bluetooth_disabled',
    'bluetooth_searching',
    'blur_circular',
    'blur_linear',
    'blur_off',
    'blur_on',
    'book',
    'bookmark',
    'bookmark_border',
    'border_all',
    'border_bottom',
    'border_clear',
    'border_color',
    'border_horizontal',
    'border_inner',
    'border_left',
    'border_outer',
    'border_right',
    'border_style',
    'border_top',
    'border_vertical',
    'branding_watermark',
    'brightness_1',
    'brightness_2',
    'brightness_3',
    'brightness_4',
    'brightness_5',
    'brightness_6',
    'brightness_7',
    'brightness_auto',
    'brightness_high',
    'brightness_low',
    'brightness_medium',
    'broken_image',
    'brush',
    'bubble_chart',
    'bug_report',
    'build',
    'burst_mode',
    'business',
    'business_center',
    'cached',
    'cake',
    'call',
    'call_end',
    'call_made',
    'call_merge',
    'call_missed',
    'call_missed_outgoing',
    'call_received',
    'call_split',
    'call_to_action',
    'camera',
    'camera_alt',
    'camera_enhance',
    'camera_front',
    'camera_rear',
    'camera_roll',
    'cancel',
    'card_giftcard',
    'card_membership',
    'card_travel',
    'casino',
    'cast',
    'cast_connected',
    'center_focus_strong',
    'center_focus_weak',
    'change_history',
    'chat',
    'chat_bubble',
    'chat_bubble_outline',
    'check',
    'check_box',
    'check_box_outline_blank',
    'check_circle',
    'chevron_left',
    'chevron_right',
    'child_care',
    'child_friendly',
    'chrome_reader_mode',
    'class',
    'clear',
    'clear_all',
    'close',
    'closed_caption',
    'cloud',
    'cloud_circle',
    'cloud_done',
    'cloud_download',
    'cloud_off',
    'cloud_queue',
    'cloud_upload',
    'code',
    'collections',
    'collections_bookmark',
    'color_lens',
    'colorize',
    'comment',
    'compare',
    'compare_arrows',
    'computer',
    'confirmation_number',
    'contact_mail',
    'contact_phone',
    'contacts',
    'content_copy',
    'content_cut',
    'content_paste',
    'control_point',
    'control_point_duplicate',
    'copyright',
    'create',
    'create_new_folder',
    'credit_card',
    'crop',
    'crop_16_9',
    'crop_3_2',
    'crop_5_4',
    'crop_7_5',
    'crop_din',
    'crop_free',
    'crop_landscape',
    'crop_original',
    'crop_portrait',
    'crop_rotate',
    'crop_square',
    'dashboard',
    'data_usage',
    'date_range',
    'dehaze',
    'delete',
    'delete_forever',
    'delete_sweep',
    'description',
    'desktop_mac',
    'desktop_windows',
    'details',
    'developer_board',
    'developer_mode',
    'device_hub',
    'devices',
    'devices_other',
    'dialer_sip',
    'dialpad',
    'directions',
    'directions_bike',
    'directions_boat',
    'directions_bus',
    'directions_car',
    'directions_railway',
    'directions_run',
    'directions_subway',
    'directions_transit',
    'directions_walk',
    'disc_full',
    'dns',
    'do_not_disturb',
    'do_not_disturb_alt',
    'do_not_disturb_off',
    'do_not_disturb_on',
    'dock',
    'domain',
    'done',
    'done_all',
    'donut_large',
    'donut_small',
    'drafts',
    'drag_handle',
    'drive_eta',
    'dvr',
    'edit',
    'edit_location',
    'eject',
    'email',
    'enhanced_encryption',
    'equalizer',
    'error',
    'error_outline',
    'euro_symbol',
    'ev_station',
    'event',
    'event_available',
    'event_busy',
    'event_note',
    'event_seat',
    'exit_to_app',
    'expand_less',
    'expand_more',
    'explicit',
    'explore',
    'exposure',
    'exposure_neg_1',
    'exposure_neg_2',
    'exposure_plus_1',
    'exposure_plus_2',
    'exposure_zero',
    'extension',
    'face',
    'fast_forward',
    'fast_rewind',
    'favorite',
    'favorite_border',
    'featured_play_list',
    'featured_video',
    'feedback',
    'fiber_dvr',
    'fiber_manual_record',
    'fiber_new',
    'fiber_pin',
    'fiber_smart_record',
    'file_download',
    'file_upload',
    'filter',
    'filter_1',
    'filter_2',
    'filter_3',
    'filter_4',
    'filter_5',
    'filter_6',
    'filter_7',
    'filter_8',
    'filter_9',
    'filter_9_plus',
    'filter_b_and_w',
    'filter_center_focus',
    'filter_drama',
    'filter_frames',
    'filter_hdr',
    'filter_list',
    'filter_none',
    'filter_tilt_shift',
    'filter_vintage',
    'find_in_page',
    'find_replace',
    'fingerprint',
    'first_page',
    'fitness_center',
    'flag',
    'flare',
    'flash_auto',
    'flash_off',
    'flash_on',
    'flight',
    'flight_land',
    'flight_takeoff',
    'flip',
    'flip_to_back',
    'flip_to_front',
    'folder',
    'folder_open',
    'folder_shared',
    'folder_special',
    'font_download',
    'format_align_center',
    'format_align_justify',
    'format_align_left',
    'format_align_right',
    'format_bold',
    'format_clear',
    'format_color_fill',
    'format_color_reset',
    'format_color_text',
    'format_indent_decrease',
    'format_indent_increase',
    'format_italic',
    'format_line_spacing',
    'format_list_bulleted',
    'format_list_numbered',
    'format_paint',
    'format_quote',
    'format_shapes',
    'format_size',
    'format_strikethrough',
    'format_textdirection_l_to_r',
    'format_textdirection_r_to_l',
    'format_underlined',
    'forum',
    'forward',
    'forward_10',
    'forward_30',
    'forward_5',
    'free_breakfast',
    'fullscreen',
    'fullscreen_exit',
    'functions',
    'g_translate',
    'gamepad',
    'games',
    'gavel',
    'gesture',
    'get_app',
    'gif',
    'golf_course',
    'gps_fixed',
    'gps_not_fixed',
    'gps_off',
    'grade',
    'gradient',
    'grain',
    'graphic_eq',
    'grid_off',
    'grid_on',
    'group',
    'group_add',
    'group_work',
    'hd',
    'hdr_off',
    'hdr_on',
    'hdr_strong',
    'hdr_weak',
    'headset',
    'headset_mic',
    'healing',
    'hearing',
    'help',
    'help_outline',
    'high_quality',
    'highlight',
    'highlight_off',
    'history',
    'home',
    'hot_tub',
    'hotel',
    'hourglass_empty',
    'hourglass_full',
    'http',
    'https',
    'image',
    'image_aspect_ratio',
    'import_contacts',
    'import_export',
    'important_devices',
    'inbox',
    'indeterminate_check_box',
    'info',
    'info_outline',
    'input',
    'insert_chart',
    'insert_comment',
    'insert_drive_file',
    'insert_emoticon',
    'insert_invitation',
    'insert_link',
    'insert_photo',
    'invert_colors',
    'invert_colors_off',
    'iso',
    'keyboard',
    'keyboard_arrow_down',
    'keyboard_arrow_left',
    'keyboard_arrow_right',
    'keyboard_arrow_up',
    'keyboard_backspace',
    'keyboard_capslock',
    'keyboard_hide',
    'keyboard_return',
    'keyboard_tab',
    'keyboard_voice',
    'kitchen',
    'label',
    'label_outline',
    'landscape',
    'language',
    'laptop',
    'laptop_chromebook',
    'laptop_mac',
    'laptop_windows',
    'last_page',
    'launch',
    'layers',
    'layers_clear',
    'leak_add',
    'leak_remove',
    'lens',
    'library_add',
    'library_books',
    'library_music',
    'lightbulb_outline',
    'line_style',
    'line_weight',
    'linear_scale',
    'link',
    'linked_camera',
    'list',
    'live_help',
    'live_tv',
    'local_activity',
    'local_airport',
    'local_atm',
    'local_bar',
    'local_cafe',
    'local_car_wash',
    'local_convenience_store',
    'local_dining',
    'local_drink',
    'local_florist',
    'local_gas_station',
    'local_grocery_store',
    'local_hospital',
    'local_hotel',
    'local_laundry_service',
    'local_library',
    'local_mall',
    'local_movies',
    'local_offer',
    'local_parking',
    'local_pharmacy',
    'local_phone',
    'local_pizza',
    'local_play',
    'local_post_office',
    'local_printshop',
    'local_see',
    'local_shipping',
    'local_taxi',
    'location_city',
    'location_disabled',
    'location_off',
    'location_on',
    'location_searching',
    'lock',
    'lock_open',
    'lock_outline',
    'looks',
    'looks_3',
    'looks_4',
    'looks_5',
    'looks_6',
    'looks_one',
    'looks_two',
    'loop',
    'loupe',
    'low_priority',
    'loyalty',
    'mail',
    'mail_outline',
    'map',
    'markunread',
    'markunread_mailbox',
    'memory',
    'menu',
    'merge_type',
    'message',
    'mic',
    'mic_none',
    'mic_off',
    'mms',
    'mode_comment',
    'mode_edit',
    'monetization_on',
    'money_off',
    'monochrome_photos',
    'mood',
    'mood_bad',
    'more',
    'more_horiz',
    'more_vert',
    'motorcycle',
    'mouse',
    'move_to_inbox',
    'movie',
    'movie_creation',
    'movie_filter',
    'multiline_chart',
    'music_note',
    'music_video',
    'my_location',
    'nature',
    'nature_people',
    'navigate_before',
    'navigate_next',
    'navigation',
    'near_me',
    'network_cell',
    'network_check',
    'network_locked',
    'network_wifi',
    'new_releases',
    'next_week',
    'nfc',
    'no_encryption',
    'no_sim',
    'not_interested',
    'note',
    'note_add',
    'notifications',
    'notifications_active',
    'notifications_none',
    'notifications_off',
    'notifications_paused',
    'offline_pin',
    'ondemand_video',
    'opacity',
    'open_in_browser',
    'open_in_new',
    'open_with',
    'pages',
    'pageview',
    'palette',
    'pan_tool',
    'panorama',
    'panorama_fish_eye',
    'panorama_horizontal',
    'panorama_vertical',
    'panorama_wide_angle',
    'party_mode',
    'pause',
    'pause_circle_filled',
    'pause_circle_outline',
    'payment',
    'people',
    'people_outline',
    'perm_camera_mic',
    'perm_contact_calendar',
    'perm_data_setting',
    'perm_device_information',
    'perm_identity',
    'perm_media',
    'perm_phone_msg',
    'perm_scan_wifi',
    'person',
    'person_add',
    'person_outline',
    'person_pin',
    'person_pin_circle',
    'personal_video',
    'pets',
    'phone',
    'phone_android',
    'phone_bluetooth_speaker',
    'phone_forwarded',
    'phone_in_talk',
    'phone_iphone',
    'phone_locked',
    'phone_missed',
    'phone_paused',
    'phonelink',
    'phonelink_erase',
    'phonelink_lock',
    'phonelink_off',
    'phonelink_ring',
    'phonelink_setup',
    'photo',
    'photo_album',
    'photo_camera',
    'photo_filter',
    'photo_library',
    'photo_size_select_actual',
    'photo_size_select_large',
    'photo_size_select_small',
    'picture_as_pdf',
    'picture_in_picture',
    'picture_in_picture_alt',
    'pie_chart',
    'pie_chart_outlined',
    'pin_drop',
    'place',
    'play_arrow',
    'play_circle_filled',
    'play_circle_outline',
    'play_for_work',
    'playlist_add',
    'playlist_add_check',
    'playlist_play',
    'plus_one',
    'poll',
    'polymer',
    'pool',
    'portable_wifi_off',
    'portrait',
    'power',
    'power_input',
    'power_settings_new',
    'pregnant_woman',
    'present_to_all',
    'print',
    'priority_high',
    'public',
    'publish',
    'query_builder',
    'question_answer',
    'queue',
    'queue_music',
    'queue_play_next',
    'radio',
    'radio_button_checked',
    'radio_button_unchecked',
    'rate_review',
    'receipt',
    'recent_actors',
    'record_voice_over',
    'redeem',
    'redo',
    'refresh',
    'remove',
    'remove_circle',
    'remove_circle_outline',
    'remove_from_queue',
    'remove_red_eye',
    'remove_shopping_cart',
    'reorder',
    'repeat',
    'repeat_one',
    'replay',
    'replay_10',
    'replay_30',
    'replay_5',
    'reply',
    'reply_all',
    'report',
    'report_problem',
    'restaurant',
    'restaurant_menu',
    'restore',
    'restore_page',
    'ring_volume',
    'room',
    'room_service',
    'rotate_90_degrees_ccw',
    'rotate_left',
    'rotate_right',
    'rounded_corner',
    'router',
    'rowing',
    'rss_feed',
    'rv_hookup',
    'satellite',
    'save',
    'scanner',
    'schedule',
    'school',
    'screen_lock_landscape',
    'screen_lock_portrait',
    'screen_lock_rotation',
    'screen_rotation',
    'screen_share',
    'sd_card',
    'sd_storage',
    'search',
    'security',
    'select_all',
    'send',
    'sentiment_dissatisfied',
    'sentiment_neutral',
    'sentiment_satisfied',
    'sentiment_very_dissatisfied',
    'sentiment_very_satisfied',
    'settings',
    'settings_applications',
    'settings_backup_restore',
    'settings_bluetooth',
    'settings_brightness',
    'settings_cell',
    'settings_ethernet',
    'settings_input_antenna',
    'settings_input_component',
    'settings_input_composite',
    'settings_input_hdmi',
    'settings_input_svideo',
    'settings_overscan',
    'settings_phone',
    'settings_power',
    'settings_remote',
    'settings_system_daydream',
    'settings_voice',
    'share',
    'shop',
    'shop_two',
    'shopping_basket',
    'shopping_cart',
    'short_text',
    'show_chart',
    'shuffle',
    'signal_cellular_4_bar',
    'signal_cellular_connected_no_internet_4_bar',
    'signal_cellular_no_sim',
    'signal_cellular_null',
    'signal_cellular_off',
    'signal_wifi_4_bar',
    'signal_wifi_4_bar_lock',
    'signal_wifi_off',
    'sim_card',
    'sim_card_alert',
    'skip_next',
    'skip_previous',
    'slideshow',
    'slow_motion_video',
    'smartphone',
    'smoke_free',
    'smoking_rooms',
    'sms',
    'sms_failed',
    'snooze',
    'sort',
    'sort_by_alpha',
    'spa',
    'space_bar',
    'speaker',
    'speaker_group',
    'speaker_notes',
    'speaker_notes_off',
    'speaker_phone',
    'spellcheck',
    'star',
    'star_border',
    'star_half',
    'stars',
    'stay_current_landscape',
    'stay_current_portrait',
    'stay_primary_landscape',
    'stay_primary_portrait',
    'stop',
    'stop_screen_share',
    'storage',
    'store',
    'store_mall_directory',
    'straighten',
    'streetview',
    'strikethrough_s',
    'style',
    'subdirectory_arrow_left',
    'subdirectory_arrow_right',
    'subject',
    'subscriptions',
    'subtitles',
    'subway',
    'supervisor_account',
    'surround_sound',
    'swap_calls',
    'swap_horiz',
    'swap_vert',
    'swap_vertical_circle',
    'switch_camera',
    'switch_video',
    'sync',
    'sync_disabled',
    'sync_problem',
    'system_update',
    'system_update_alt',
    'tab',
    'tab_unselected',
    'tablet',
    'tablet_android',
    'tablet_mac',
    'tag_faces',
    'tap_and_play',
    'terrain',
    'text_fields',
    'text_format',
    'textsms',
    'texture',
    'theaters',
    'thumb_down',
    'thumb_up',
    'thumbs_up_down',
    'time_to_leave',
    'timelapse',
    'timeline',
    'timer',
    'timer_10',
    'timer_3',
    'timer_off',
    'title',
    'toc',
    'today',
    'toll',
    'tonality',
    'touch_app',
    'toys',
    'track_changes',
    'traffic',
    'train',
    'tram',
    'transfer_within_a_station',
    'transform',
    'translate',
    'trending_down',
    'trending_flat',
    'trending_up',
    'tune',
    'turned_in',
    'turned_in_not',
    'tv',
    'unarchive',
    'undo',
    'unfold_less',
    'unfold_more',
    'update',
    'usb',
    'verified_user',
    'vertical_align_bottom',
    'vertical_align_center',
    'vertical_align_top',
    'vibration',
    'video_call',
    'video_label',
    'video_library',
    'videocam',
    'videocam_off',
    'videogame_asset',
    'view_agenda',
    'view_array',
    'view_carousel',
    'view_column',
    'view_comfy',
    'view_compact',
    'view_day',
    'view_headline',
    'view_list',
    'view_module',
    'view_quilt',
    'view_stream',
    'view_week',
    'vignette',
    'visibility',
    'visibility_off',
    'voice_chat',
    'voicemail',
    'volume_down',
    'volume_mute',
    'volume_off',
    'volume_up',
    'vpn_key',
    'vpn_lock',
    'wallpaper',
    'warning',
    'watch',
    'watch_later',
    'wb_auto',
    'wb_cloudy',
    'wb_incandescent',
    'wb_iridescent',
    'wb_sunny',
    'wc',
    'web',
    'web_asset',
    'weekend',
    'whatshot',
    'widgets',
    'wifi',
    'wifi_lock',
    'wifi_tethering',
    'work',
    'wrap_text',
    'youtube_searched_for',
    'zoom_in',
    'zoom_out',
    'zoom_out_map',
  ];
}
